package com.csidigital.rh.shared.enumeration;

public enum ContractType {
    PERMANENT_EMPLOYMENT_CONTRACT,SUMMER_INTERNSHIP,END_OF_STUDY_PROJECT,INVITATION,DEVELOPMENT_INTERNSHIP,CDI,CDD,CIVP,FREELANCE,
    ALTERNATION,SUB_CONTRACTING,CTT
}
